### ISSUE TITLE
Prevent bot from posting the same pair of characters

### ISSUE THREAD

**Issue by Frizz925** [Frizz925/shippostbot#1]
Need to find a way for the bot to avoid selecting same pair of characters regardless of the source and character's order.

Current solution is to use NoSQL database (eg. MongoDB, AWS DynamoDB) to store previously picked characters. However, an abstraction need to be made on top of the database connection in order to provide testability.

**Comment by frizz925** [comment]
Won't do as it may incur additional running cost for the bot.
