### ISSUE TITLE
Setup AWS CloudWatch alarm resource

### ISSUE THREAD

**Issue by Frizz925** [Frizz925/shippostbot#8]
When the bot is failing to post over the period of time, it's actually hard to tell that it is failing until it's noticed that the bot actually stops posting. One way to overcome this problem is by setting up a AWS CloudWatch alarm based on Lambda's error metrics and trigger it under a certain condition. 

The condition would be for average number of errors that is more than 1 over the period of 1 hour (assuming the bot posts every 30 mins), it should trigger the alarm.

**Comment by frizz925** [comment]
Done, although manually through the AWS console (no Terraform)
